# Generated by Django 2.2.3 on 2019-07-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Grade',
            new_name='grade',
        ),
    ]
