# Generated by Django 2.2.3 on 2019-07-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190719_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Creator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Instructor',
            new_name='instructor',
        ),
    ]
