# Generated by Django 2.2.3 on 2019-07-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190719_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor',
            new_name='instructors',
        ),
    ]
