# Generated by Django 2.2.3 on 2019-07-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190719_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='descritpion',
            new_name='description',
        ),
    ]
