# Generated by Django 2.2.3 on 2019-07-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190719_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='Creator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Creator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='Creator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='Creator',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='content',
            name='title',
        ),
    ]
