# Generated by Django 2.2.3 on 2019-07-21 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190720_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name__in': ['Instructors']}, related_name='courses_instructed', related_query_name='instruct_in_course', to=settings.AUTH_USER_MODEL),
        ),
    ]
