# Generated by Django 2.2.3 on 2019-07-21 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190721_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_url',
        ),
    ]
