# Generated by Django 2.2.3 on 2019-07-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190725_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
